### ISSUE TITLE
knacksteem.org IP address can't be found. 

### ISSUE THREAD

**Issue by jubreal** [knacksteem/knacksteem.org#29]
#### Expected behavior
Users should be routed to and be able to access and use the knacksteem.org landing page. 

#### Actual behavior

The website couldn't be reached at the server IP address can't be found. 
 

#### How to reproduce
- Launch your chrome web browser.
- Enter "https://www.knacksteem.org" into the address bar and wait for it to load. 

It would be observed that the page fails to load. 

* Browser/App version: Chrome version 68.0.3440.91
* Operating system: Android version 6.0

#### Recording Of The Bug

https://youtu.be/71YvIimnhBI

**Comment by onozasi** [comment]
Hello @jubreal, Thank you for reporting this issue. However, I could not reproduce this behavior on my device. It's working perfectly here. 
I suspect that you have a poor internet connection. Can you try this behavior on another device or perhaps using a PC so that you can share with us the error message displayed in the console?

**Comment by jubreal** [comment]
I will try that on my PC once I get hold of my PC.  I tried it on other
devices though and couldn't access it

**Comment by jubreal** [comment]
The issue seems to occur when "www" is added to the knacksteem.org

**Comment by onozasi** [comment]
The site is not configured to work with "www."  This is intentional and not a bug. Now that you have pointed it out, I will add it to the IP redirect. So that each time you input "www,"  the site will work correctly. 👍
