### ISSUE TITLE
Reply button of a post preview is not responsive.

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#99]
#### Expected behavior
I laud the implementation of many new features on Knacksteem's front-end. However, some basic features still need fixes. An example is the reply button on a  post's preview on feeds. Firstly, I didn't expect the reply button to be available on the preview of a post. It would be weird replying a post that was really read. But, if it isn't considered awkward to reply a post that wasn't read, I expected the reply button to respond to my command by opening the comments post editor.

#### Actual behavior
Clicking the reply button does nothing. Hovering my mouse around that area suggested that it can be clicked and would perform an action but, nothing works.

#### How to reproduce
- Goto [Knacksteem](https://knacksteem.org)
- Login 
- Click the reply button on any of the post preview available on the feed. 

* Browser/App version: Google Chrome
* Operating system: Windows 7

This error is persistent on my mobile phone so it's not a problem peculiar to a device, browser or OS.

**Comment by onozasi** [comment]
You are right, the "reply" button on the post preview section looks a little bit redundant since a user is expected to read the post content first before responding. 

Clicking on it does nothing because it has not been routed to the user's comment section. Implementing that may be a little bit out of place since we'll consider striping it out from that section.

**Comment by HarryHeights** [comment]
Oh okay great

**Comment by codingdefined** [comment]
@onozasi I will remove the reply button from the Post Preview.

**Comment by onozasi** [comment]
Okay cool.
